########################
##  git clone https://github.com/harryliu123/docker-learn.git
##  cd docker-learn
##  docker build -t helloworld:java . --no-cache -f Dockerfile-java
##  docker run -it  helloworld:java
########################

FROM jlrigau/maven-git as builder
MAINTAINER harry
RUN git clone https://github.com/harryliu123/docker-learn.git
WORKDIR /docker-learn/helloworld-java/my-app
RUN ls && pwd
RUN mvn package

FROM openjdk
MAINTAINER harry
COPY --from=builder /docker-learn/helloworld-java/my-app/target/my-app-1.0-SNAPSHOT.jar /my-app-1.0-SNAPSHOT.jar
CMD "java -jar /my-app-1.0-SNAPSHOT.jar"
